//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAG_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Chemistry Group 1,0,1,2
        ///1,Chemistry Group 2,3,4,5
        ///2,Chemistry Group 3,6,7,8
        ///3,Chemistry Group 4,9,10,11
        ///4,Chemistry Group 5,12,13,14
        ///5,Chemistry Group 6,15,16,17
        ///6,Chemistry Group 7,18,19,20
        ///7,Chemistry Group 8,21,22,23
        ///8,Chemistry Group 9,24,25,26
        ///9,Chemistry Group 10,27,28,29
        ///10,Chemistry Group 11,30,31,32
        ///11,Chemistry Group 12,33,34,35
        ///.
        /// </summary>
        internal static string PagGroup {
            get {
                return ResourceManager.GetString("PagGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000,1.1 Moles determination Activity 1 - Determination of the composition of copper(II) carbonate basic
        ///001,1.2 Moles determination Activity 2 - Determination of relative atomic mass of magnesium
        ///002,1.3 Moles determination Activity 3 - Determination of the formula for magnesium oxide
        ///003,2.1 Acid-base titration Activity 1 - Determination of concentration of hydrochloric acid
        ///004,2.2 Acid-base titration Activity 2 - Determination of the molar mass of an acid
        ///005,2.3 Acid-base titration Activity 3 - Ide [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PagList {
            get {
                return ResourceManager.GetString("PagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1,0
        ///0,2,1
        ///0,3,2
        ///0,4,3
        ///0,5,4
        ///0,9,5
        ///0,10,6
        ///0,26,7
        ///0,29,8
        ///0,31,9
        ///0,32,10
        ///1,1,0
        ///1,2,1
        ///1,3,2
        ///1,4,3
        ///1,5,4
        ///1,9,5
        ///1,10,6
        ///1,29,7
        ///1,31,8
        ///1,32,9
        ///1,26,10
        ///2,1,0
        ///2,2,1
        ///2,3,2
        ///2,4,3
        ///2,5,4
        ///2,9,5
        ///2,10,6
        ///2,29,7
        ///2,31,8
        ///2,32,9
        ///3,1,0
        ///3,2,1
        ///3,3,2
        ///3,4,3
        ///3,5,4
        ///3,9,5
        ///3,10,6
        ///3,13,7
        ///3,19,8
        ///3,20,9
        ///3,29,10
        ///3,31,11
        ///3,32,12
        ///4,1,0
        ///4,2,1
        ///4,3,2
        ///4,4,3
        ///4,5,4
        ///4,9,5
        ///4,10,6
        ///4,13,7
        ///4,19,8
        ///4,20,9
        ///4,26,10
        ///4,29,11
        ///4,31,12
        ///4,32,13
        ///5,1,0
        ///5,2,1
        ///5,3,2
        ///5,4,3
        ///5,5,4
        ///5,9,5
        ///5,10,6
        ///5,13,7
        ///5,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PagSkillRelation {
            get {
                return ResourceManager.GetString("PagSkillRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000,Apply investigative approaches and methods to practical work
        ///001,Safely and correctly use a range of practical equipment and materials
        ///002,Follow written instructions
        ///003,Make and record observations/measurements
        ///004,Keep appropriate records of experimental activities
        ///005,Present information and data in a scientific way
        ///006,Use appropriate software and tools to process data; carry out research and report findings
        ///007,Use online and offline research skills including websites; textbooks and other p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillList {
            get {
                return ResourceManager.GetString("SkillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1
        ///1,1
        ///2,1
        ///3,1
        ///4,1
        ///5,1
        ///6,1
        ///7,1
        ///8,1
        ///9,1
        ///10,1
        ///11,1
        ///12,1
        ///13,1
        ///14,1
        ///15,1
        ///16,1
        ///17,1
        ///18,1
        ///19,1
        ///20,1
        ///21,1
        ///22,1
        ///23,1
        ///24,1
        ///25,1
        ///26,1
        ///27,1
        ///28,1
        ///29,5
        ///30,5
        ///31,5
        ///32,5
        ///33,5
        ///.
        /// </summary>
        internal static string SkillRequirement {
            get {
                return ResourceManager.GetString("SkillRequirement", resourceCulture);
            }
        }
    }
}
